#!/usr/bin/env python3
"""
web_research.py - Search arXiv for papers and generate research corpus.

Usage:
    python web_research.py --topic "autonomous AI agents" --limit 10 --output-dir ./output

Outputs:
    papers.json - JSON array of paper metadata
    research-corpus.md - Markdown-formatted research corpus
"""

import argparse
import json
import os
import sys
import urllib.parse
import urllib.request
import re
from datetime import datetime

def search_arxiv(topic, limit=10):
    """Search arXiv API for papers matching the topic."""
    base_url = "http://export.arxiv.org/api/query"
    
    # Search for papers matching the topic
    query = f"all:{urllib.parse.quote(topic)}"
    params = {
        "search_query": query,
        "start": 0,
        "max_results": limit,
        "sortBy": "relevance",
        "sortOrder": "descending"
    }
    
    query_string = "&".join(f"{k}={v}" for k, v in params.items())
    url = f"{base_url}?{query_string}"
    
    print(f"Searching arXiv: {topic}")
    print(f"URL: {url}")
    
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            content = response.read().decode("utf-8")
    except Exception as e:
        print(f"Error fetching from arXiv: {e}", file=sys.stderr)
        return []
    
    # Parse XML response
    papers = []
    
    # Extract entry elements using regex (simpler than adding xml dependencies)
    entry_pattern = r"<entry>(.*?)</entry>"
    entries = re.findall(entry_pattern, content, re.DOTALL)
    
    for entry in entries:
        paper = {}
        
        # Extract title
        title_match = re.search(r"<title>(.*?)</title>", entry, re.DOTALL)
        paper["title"] = title_match.group(1).strip() if title_match else "Untitled"
        
        # Extract summary/abstract
        summary_match = re.search(r"<summary>(.*?)</summary>", entry, re.DOTALL)
        paper["abstract"] = summary_match.group(1).strip() if summary_match else ""
        
        # Extract authors
        authors = []
        author_matches = re.findall(r"<name>(.*?)</name>", entry)
        for name in author_matches:
            authors.append({"name": name.strip()})
        paper["authors"] = authors
        
        # Extract published date
        published_match = re.search(r"<published>(.*?)</published>", entry)
        if published_match:
            date_str = published_match.group(1)[:10]  # YYYY-MM-DD
            paper["year"] = date_str[:4]
        
        # Extract id
        id_match = re.search(r"<id>(.*?)</id>", entry)
        if id_match:
            paper_id = id_match.group(1).strip()
            # Convert to PDF URL
            paper["url"] = paper_id.replace("http://arxiv.org/abs/", "http://arxiv.org/pdf/") + "v1"
            paper["paperId"] = paper["url"]
        
        paper["citationCount"] = 0
        paper["concepts"] = []
        
        papers.append(paper)
    
    print(f"Found {len(papers)} papers")
    return papers


def generate_markdown_corpus(papers, topic):
    """Generate markdown-formatted research corpus from papers."""
    lines = []
    lines.append(f"# Research Corpus: {topic}")
    lines.append("")
    lines.append(f"*Generated by web_research.py - {len(papers)} papers*")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    for i, paper in enumerate(papers, 1):
        # Title
        lines.append(f"## {paper.get('title', 'Untitled')}")
        
        # Year and citations
        year = paper.get("year", "Unknown")
        citations = paper.get("citationCount", 0)
        lines.append(f"**Year:** {year} | **Citations:** {citations}")
        
        # Authors
        authors = paper.get("authors", [])
        if authors:
            author_names = ", ".join(a["name"] for a in authors)
            lines.append(f"**Authors:** {author_names}")
        
        lines.append("")
        
        # Abstract
        abstract = paper.get("abstract", "")
        lines.append("### Abstract")
        lines.append(abstract)
        lines.append("")
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Search arXiv and generate research corpus")
    parser.add_argument("--topic", required=True, help="Search topic/keyword")
    parser.add_argument("--limit", type=int, default=10, help="Maximum number of papers (default: 10)")
    parser.add_argument("--output-dir", required=True, help="Output directory for papers.json and research-corpus.md")
    
    args = parser.parse_args()
    
    # Create output directory if it doesn't exist
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Search arXiv
    papers = search_arxiv(args.topic, args.limit)
    
    if not papers:
        print("No papers found.", file=sys.stderr)
        sys.exit(1)
    
    # Write papers.json
    papers_json_path = os.path.join(args.output_dir, "papers.json")
    with open(papers_json_path, "w", encoding="utf-8") as f:
        json.dump(papers, f, indent=2, ensure_ascii=False)
    print(f"Written: {papers_json_path}")
    
    # Write research-corpus.md
    corpus_md_path = os.path.join(args.output_dir, "research-corpus.md")
    corpus_content = generate_markdown_corpus(papers, args.topic)
    with open(corpus_md_path, "w", encoding="utf-8") as f:
        f.write(corpus_content)
    print(f"Written: {corpus_md_path}")
    
    print("Done.")


if __name__ == "__main__":
    main()